# Generated by Django 4.0.4 on 2022-04-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='1', max_length=20)),
                ('birth', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
